#!/bin/sh

# source init_lib
. /etc/scripts/init_lib.sh

STORAGE_DIR=/mnt/storage
RAWFS_DIR=/mnt/rawfs

# busybox
MOUNT=/bin/mount
IFCONFIG=/sbin/ifconfig
INETD=/usr/sbin/inetd
SLEEP=/bin/sleep
PYTHON=/usr/bin/python
POWEROFF=/sbin/poweroff
CAT=/bin/cat
GREP=/bin/grep
CUT=/usr/bin/cut
ZCAT=/bin/zcat
LN="/bin/ln -s"

# abcbox
ABCBOX=/bin/abcbox
GET_INFO=/bin/get_info
GET_STORAGE_PROP=/bin/get_storage_prop
RFBI_REFRESH=/bin/rfbi_refresh
USB_TS_ENABLE=/bin/usb_ts_enable
FB_WRITE=/bin/fb_write
KX_CHECKER=/bin/kx_checker
REBOOT_INTO=/bin/reboot_into

$LN $ABCBOX $GET_INFO
$LN $ABCBOX $GET_STORAGE_PROP
$LN $ABCBOX $RFBI_REFRESH
$LN $ABCBOX $USB_TS_ENABLE
$LN $ABCBOX $FB_WRITE
$LN $ABCBOX $KX_CHECKER
$LN $ABCBOX $REBOOT_INTO

# Prepare filesystem
$MOUNT -t proc proc /proc
$MOUNT -t usbfs none /proc/bus/usb
$MOUNT -t sysfs sysfs /sys
$MOUNT -t devpts devpts /dev/pts
$MOUNT -t tmpfs tmpfs /dev/shm
ln -s /proc/mounts /etc/mtab

# Get board and product information
PRODUCT_NAME=`$GET_INFO p`
PRODUCT_REVISION=`$GET_INFO r`

set_charger_state lo

log "init get_info - PRODUCT $PRODUCT_NAME ($PRODUCT_REVISION) - AOSFILENAME $AOS_FILENAME"

wait_block_devices rawfs

echo 2048 > /sys/block/mmcblk0/queue/max_sectors_kb
echo 2048 > /sys/block/mmcblk1/queue/max_sectors_kb

mount_p rawfs || init_fail "mount rawfs fail"

display_banner $PRODUCT_NAME $PRODUCT_REVISION

# make permanent reboot in sde
$REBOOT_INTO -s sde

# check init file
$KX_CHECKER -f /mnt/rawfs/init
ki_status=$?

# XXX: do hdd_lock checks for A70H
wait_block_devices storage

mount_p storage || init_fail "mount storage fail"

STORAGE_DEV=`get_mount_info d storage`
RAWFS_DEV=`get_mount_info d rawfs`

$USB_TS_ENABLE --detach

CONFIG_FILE="$STORAGE_DIR/kboot/conf/config.ini"
SECTION="init"

eval `sed -e 's/[[:space:]]*\=[[:space:]]*/=/g' \
    -e 's/;.*$//' \
    -e 's/[[:space:]]*$//' \
    -e 's/^[[:space:]]*//' \
    -e "s/^\(.*\)=\([^\"']*\)$/\1=\"\2\"/" \
   < $CONFIG_FILE \
    | sed -n -e "/^\[$SECTION\]/,/^\s*\[/{/^[^;].*\=.*/p;}"`

IP="192.168.0.1"
if [[ $usbip ]]; then
	IP="$usbip"
fi
if [[ $telnet == "1" ]]; then
	$IFCONFIG lo 127.0.0.1 netmask 255.0.0.0 up
	$IFCONFIG usb0 $IP up
	$INETD
fi

BOARDNUM=0

case "$PRODUCT_NAME" in
	A28)	BOARDNUM=1
	;;
	A32)	BOARDNUM=2
	;;
	A32SD)	BOARDNUM=3
	;;
	A35*)	BOARDNUM=4
	;;
	A43)	BOARDNUM=5
	;;
	A70S)	BOARDNUM=6
	;;
	A70H*)	BOARDNUM=7
	;;
	A101IT)	BOARDNUM=8
	;;
esac

$PYTHON /opt/menu/kboot.py $BOARDNUM $STORAGE_DIR $ki_status

$POWEROFF -f

# EOF
